/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as KarirRouteImport } from './routes/karir'
import { Route as KlienRouteImport } from './routes/klien'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as CrmIndexRouteImport } from './routes/crm/index'
import { Route as CrmClientsRouteImport } from './routes/crm/clients'
import { Route as CrmLeadsRouteImport } from './routes/crm/leads'
import { Route as CrmLoginRouteImport } from './routes/crm/login'
import { Route as CrmProjectsRouteImport } from './routes/crm/projects'
import { Route as LayananIndexRouteImport } from './routes/layanan/index'
import { Route as LayananSlugRouteImport } from './routes/layanan/$slug'
import { Route as CrmClientsIdRouteImport } from './routes/crm/clients.$id'
import { Route as CrmLeadsIdRouteImport } from './routes/crm/leads.$id'
import { Route as CrmProjectsIdRouteImport } from './routes/crm/projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const KarirRoute = KarirRouteImport.update({
  id: '/karir',
  path: '/karir',
  getParentRoute: () => rootRouteImport,
} as any)
const KlienRoute = KlienRouteImport.update({
  id: '/klien',
  path: '/klien',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const CrmClientsRoute = CrmClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLeadsRoute = CrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLoginRoute = CrmLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CrmRoute,
} as any)
const CrmProjectsRoute = CrmProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => CrmRoute,
} as any)
const LayananIndexRoute = LayananIndexRouteImport.update({
  id: '/layanan/',
  path: '/layanan/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananSlugRoute = LayananSlugRouteImport.update({
  id: '/layanan/$slug',
  path: '/layanan/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmClientsIdRoute = CrmClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CrmClientsRoute,
} as any)
const CrmLeadsIdRoute = CrmLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CrmLeadsRoute,
} as any)
const CrmProjectsIdRoute = CrmProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CrmProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/karir': typeof KarirRoute
  '/klien': typeof KlienRoute
  '/kontak': typeof KontakRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/crm/clients': typeof CrmClientsRouteWithChildren
  '/crm/leads': typeof CrmLeadsRouteWithChildren
  '/crm/login': typeof CrmLoginRoute
  '/crm/projects': typeof CrmProjectsRouteWithChildren
  '/layanan/$slug': typeof LayananSlugRoute
  '/crm/': typeof CrmIndexRoute
  '/layanan/': typeof LayananIndexRoute
  '/crm/clients/$id': typeof CrmClientsIdRoute
  '/crm/leads/$id': typeof CrmLeadsIdRoute
  '/crm/projects/$id': typeof CrmProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/karir': typeof KarirRoute
  '/klien': typeof KlienRoute
  '/kontak': typeof KontakRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/crm/clients': typeof CrmClientsRouteWithChildren
  '/crm/leads': typeof CrmLeadsRouteWithChildren
  '/crm/login': typeof CrmLoginRoute
  '/crm/projects': typeof CrmProjectsRouteWithChildren
  '/layanan/$slug': typeof LayananSlugRoute
  '/crm': typeof CrmIndexRoute
  '/layanan': typeof LayananIndexRoute
  '/crm/clients/$id': typeof CrmClientsIdRoute
  '/crm/leads/$id': typeof CrmLeadsIdRoute
  '/crm/projects/$id': typeof CrmProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/crm': typeof CrmRouteWithChildren
  '/karir': typeof KarirRoute
  '/klien': typeof KlienRoute
  '/kontak': typeof KontakRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
  '/crm/clients': typeof CrmClientsRouteWithChildren
  '/crm/leads': typeof CrmLeadsRouteWithChildren
  '/crm/login': typeof CrmLoginRoute
  '/crm/projects': typeof CrmProjectsRouteWithChildren
  '/layanan/$slug': typeof LayananSlugRoute
  '/crm/': typeof CrmIndexRoute
  '/layanan/': typeof LayananIndexRoute
  '/crm/clients/$id': typeof CrmClientsIdRoute
  '/crm/leads/$id': typeof CrmLeadsIdRoute
  '/crm/projects/$id': typeof CrmProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/crm'
    | '/karir'
    | '/klien'
    | '/kontak'
    | '/portfolio'
    | '/sitemap.xml'
    | '/tentang'
    | '/crm/clients'
    | '/crm/leads'
    | '/crm/login'
    | '/crm/projects'
    | '/layanan/$slug'
    | '/crm/'
    | '/layanan/'
    | '/crm/clients/$id'
    | '/crm/leads/$id'
    | '/crm/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/karir'
    | '/klien'
    | '/kontak'
    | '/portfolio'
    | '/sitemap.xml'
    | '/tentang'
    | '/crm/clients'
    | '/crm/leads'
    | '/crm/login'
    | '/crm/projects'
    | '/layanan/$slug'
    | '/crm'
    | '/layanan'
    | '/crm/clients/$id'
    | '/crm/leads/$id'
    | '/crm/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/crm'
    | '/karir'
    | '/klien'
    | '/kontak'
    | '/portfolio'
    | '/sitemap.xml'
    | '/tentang'
    | '/crm/clients'
    | '/crm/leads'
    | '/crm/login'
    | '/crm/projects'
    | '/layanan/$slug'
    | '/crm/'
    | '/layanan/'
    | '/crm/clients/$id'
    | '/crm/leads/$id'
    | '/crm/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CrmRoute: typeof CrmRouteWithChildren
  KarirRoute: typeof KarirRoute
  KlienRoute: typeof KlienRoute
  KontakRoute: typeof KontakRoute
  PortfolioRoute: typeof PortfolioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TentangRoute: typeof TentangRoute
  LayananSlugRoute: typeof LayananSlugRoute
  LayananIndexRoute: typeof LayananIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karir': {
      id: '/karir'
      path: '/karir'
      fullPath: '/karir'
      preLoaderRoute: typeof KarirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klien': {
      id: '/klien'
      path: '/klien'
      fullPath: '/klien'
      preLoaderRoute: typeof KlienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/clients': {
      id: '/crm/clients'
      path: '/clients'
      fullPath: '/crm/clients'
      preLoaderRoute: typeof CrmClientsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/leads': {
      id: '/crm/leads'
      path: '/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof CrmLeadsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/login': {
      id: '/crm/login'
      path: '/login'
      fullPath: '/crm/login'
      preLoaderRoute: typeof CrmLoginRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/projects': {
      id: '/crm/projects'
      path: '/projects'
      fullPath: '/crm/projects'
      preLoaderRoute: typeof CrmProjectsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/layanan/': {
      id: '/layanan/'
      path: '/layanan'
      fullPath: '/layanan/'
      preLoaderRoute: typeof LayananIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan/$slug': {
      id: '/layanan/$slug'
      path: '/layanan/$slug'
      fullPath: '/layanan/$slug'
      preLoaderRoute: typeof LayananSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/clients/$id': {
      id: '/crm/clients/$id'
      path: '/$id'
      fullPath: '/crm/clients/$id'
      preLoaderRoute: typeof CrmClientsIdRouteImport
      parentRoute: typeof CrmClientsRoute
    }
    '/crm/leads/$id': {
      id: '/crm/leads/$id'
      path: '/$id'
      fullPath: '/crm/leads/$id'
      preLoaderRoute: typeof CrmLeadsIdRouteImport
      parentRoute: typeof CrmLeadsRoute
    }
    '/crm/projects/$id': {
      id: '/crm/projects/$id'
      path: '/$id'
      fullPath: '/crm/projects/$id'
      preLoaderRoute: typeof CrmProjectsIdRouteImport
      parentRoute: typeof CrmProjectsRoute
    }
  }
}

interface CrmClientsRouteChildren {
  CrmClientsIdRoute: typeof CrmClientsIdRoute
}

const CrmClientsRouteChildren: CrmClientsRouteChildren = {
  CrmClientsIdRoute: CrmClientsIdRoute,
}

const CrmClientsRouteWithChildren = CrmClientsRoute._addFileChildren(
  CrmClientsRouteChildren,
)

interface CrmLeadsRouteChildren {
  CrmLeadsIdRoute: typeof CrmLeadsIdRoute
}

const CrmLeadsRouteChildren: CrmLeadsRouteChildren = {
  CrmLeadsIdRoute: CrmLeadsIdRoute,
}

const CrmLeadsRouteWithChildren = CrmLeadsRoute._addFileChildren(
  CrmLeadsRouteChildren,
)

interface CrmProjectsRouteChildren {
  CrmProjectsIdRoute: typeof CrmProjectsIdRoute
}

const CrmProjectsRouteChildren: CrmProjectsRouteChildren = {
  CrmProjectsIdRoute: CrmProjectsIdRoute,
}

const CrmProjectsRouteWithChildren = CrmProjectsRoute._addFileChildren(
  CrmProjectsRouteChildren,
)

interface CrmRouteChildren {
  CrmClientsRoute: typeof CrmClientsRouteWithChildren
  CrmLeadsRoute: typeof CrmLeadsRouteWithChildren
  CrmLoginRoute: typeof CrmLoginRoute
  CrmProjectsRoute: typeof CrmProjectsRouteWithChildren
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmClientsRoute: CrmClientsRouteWithChildren,
  CrmLeadsRoute: CrmLeadsRouteWithChildren,
  CrmLoginRoute: CrmLoginRoute,
  CrmProjectsRoute: CrmProjectsRouteWithChildren,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CrmRoute: CrmRouteWithChildren,
  KarirRoute: KarirRoute,
  KlienRoute: KlienRoute,
  KontakRoute: KontakRoute,
  PortfolioRoute: PortfolioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TentangRoute: TentangRoute,
  LayananSlugRoute: LayananSlugRoute,
  LayananIndexRoute: LayananIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
