/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as LayananRouteImport } from './routes/layanan'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TentangRouteImport } from './routes/tentang'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const LayananRoute = LayananRouteImport.update({
  id: '/layanan',
  path: '/layanan',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kontak': typeof KontakRoute
  '/layanan': typeof LayananRoute
  '/portfolio': typeof PortfolioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tentang': typeof TentangRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/kontak' | '/layanan' | '/portfolio' | '/sitemap.xml' | '/tentang'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontak' | '/layanan' | '/portfolio' | '/sitemap.xml' | '/tentang'
  id:
    | '__root__'
    | '/'
    | '/kontak'
    | '/layanan'
    | '/portfolio'
    | '/sitemap.xml'
    | '/tentang'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontakRoute: typeof KontakRoute
  LayananRoute: typeof LayananRoute
  PortfolioRoute: typeof PortfolioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TentangRoute: typeof TentangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layanan': {
      id: '/layanan'
      path: '/layanan'
      fullPath: '/layanan'
      preLoaderRoute: typeof LayananRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontakRoute: KontakRoute,
  LayananRoute: LayananRoute,
  PortfolioRoute: PortfolioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TentangRoute: TentangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
